### ISSUE TITLE
Blur not working on firefox context menu

### ISSUE THREAD

**Issue by enzobelmont** [esjeon/kwin-forceblur#13]
i've using picom on xfce and others DEs, and firefox's context menu shows a nice blur; but in my loved plasma, blur is not working on firefox's context menus.

I've tried to find WM_CLASS id of firefox context menu's, but i am afraid that it has no one (because it is not a window of course).

Your help would be so much appreciated.

Thanks in advance.

**Comment by esjeon** [comment]
This is unfixable because KWin doesn't tell the script about context menus. Picom can handle them only because Picom itself is the compositor.

Maybe you can simply replace KWin compositor with Picom instead. I've seen people doing this.
