### ISSUE TITLE
Feature Request: Change the Blur Strenght.

### ISSUE THREAD

**Issue by SATYADAHAL** [esjeon/kwin-forceblur#32]
The blur strenght is too much. It sometimes hides the background completely. It would be awesome if we can adjust the blur strenghth.

**Comment by esjeon** [comment]
This extension only enables the blur effect.

The strength is controlled by KDE. Try searching for "blur" in System Settings.

**Comment by SATYADAHAL** [comment]
I just found out that blur strength and noise can be changed through 
1. System Settings
2. Desktop Effects 
3 . Blur
4. and Gear icon
but the problem is i might want different blur strength depending on the application.  Is there a way we can classify applications according to different blur strength.

**Comment by esjeon** [comment]
> Is there a way we can classify applications according to different blur strength.

Unfortunately, no. Blur plugin doesn't work like that atm.
