### ISSUE TITLE
Doesnt work for spotify

### ISSUE THREAD

**Issue by kvatum-20** [esjeon/kwin-forceblur#9]
This works for every other window except spotify

**Comment by esjeon** [comment]
Does Spotify client has transparent background? AFAIK, Spotify is built with Electron, which doesn't support transparent window background by default. That is, devs must 

A possible workaround is setting window opacity using KWin features. (i.e. 'Configure Special Application Settings" in window context menu). For example, I set the opacity of Visual Studio Code (also built with Electron) to 95%, and enabled blur through this script. It looks somewhat transparent, while contents are still readable.

**Comment by kvatum-20** [comment]
Thanks, working perfectly now
